project:
  output-dir: _output
  type: website

toc: true
number-sections: true
  
format:
  html:
    html-math-method: katex

website:
  title: "Test"
  navbar:
    left:
      - 01-paper2.ipynb
      - 02-notebook.ipynb