[project]
authors = ["Michael Riley <michaelriley@situsamc.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mystmd-quickstart_test"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
# altair = ">=5.4.1,<6"
# matplotlib = ">=3.9.2,<4"
# numpy = ">=2.1.3,<3"
# vega_datasets = ">=0.9.0,<0.10"
jupyterlab-myst = ">=2.4.2,<3"
quarto = ">=1.5.57,<2"
jupytext = ">=1.16.4,<2"
# mystmd = ">=1.3.17,<2"
